import type { Restaurant, Product } from "@/types";

export const mockRestaurants: (Restaurant & { id: string })[] = [
  {
    id: "1",
    name: "Burger King",
    slug: "burger-king",
    description: "Ateste izgara lezzeti ile dunyanin en sevilen burgerleri",
    ownerId: "owner1",
    address: { full: "Bagdat Cad. No:123, Kadikoy", city: "Istanbul", district: "Kadikoy", lat: 40.9862, lng: 29.0558 },
    contact: { phone: "0212 555 0001", email: "info@burgerking.com.tr" },
    cuisine: ["Burger", "Fast Food"],
    images: { logo: "", cover: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=500&fit=crop&auto=format", gallery: [] },
    hours: { monday: { open: "10:00", close: "23:00", isOpen: true }, tuesday: { open: "10:00", close: "23:00", isOpen: true }, wednesday: { open: "10:00", close: "23:00", isOpen: true }, thursday: { open: "10:00", close: "23:00", isOpen: true }, friday: { open: "10:00", close: "00:00", isOpen: true }, saturday: { open: "10:00", close: "00:00", isOpen: true }, sunday: { open: "11:00", close: "23:00", isOpen: true } },
    delivery: { fee: 9.99, minOrder: 50, estimatedTime: 30, radius: 5 },
    rating: { average: 4.5, count: 320 },
    commission: { rate: 15, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "2",
    name: "Pizza Lazza",
    slug: "pizza-lazza",
    description: "Italyan usulu el yapimi pizzalar",
    ownerId: "owner2",
    address: { full: "Istiklal Cad. No:45, Beyoglu", city: "Istanbul", district: "Beyoglu", lat: 41.0340, lng: 28.9775 },
    contact: { phone: "0212 555 0002", email: "info@pizzalazza.com" },
    cuisine: ["Pizza", "Italyan", "Makarna"],
    images: { logo: "", cover: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=500&fit=crop&auto=format", gallery: [] },
    hours: { monday: { open: "11:00", close: "23:00", isOpen: true }, tuesday: { open: "11:00", close: "23:00", isOpen: true }, wednesday: { open: "11:00", close: "23:00", isOpen: true }, thursday: { open: "11:00", close: "23:00", isOpen: true }, friday: { open: "11:00", close: "00:00", isOpen: true }, saturday: { open: "11:00", close: "00:00", isOpen: true }, sunday: { open: "12:00", close: "23:00", isOpen: true } },
    delivery: { fee: 12.99, minOrder: 60, estimatedTime: 35, radius: 4 },
    rating: { average: 4.3, count: 210 },
    commission: { rate: 12, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "3",
    name: "Kebapci Iskender",
    slug: "kebapci-iskender",
    description: "1867'den beri Iskender kebabin orijinal adresi",
    ownerId: "owner3",
    address: { full: "Ataturk Cad. No:7, Osmangazi", city: "Bursa", district: "Osmangazi", lat: 40.1885, lng: 29.0610 },
    contact: { phone: "0224 555 0003", email: "info@iskender.com.tr" },
    cuisine: ["Kebap", "Turk Mutfagi"],
    images: { logo: "", cover: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=500&fit=crop&auto=format", gallery: [] },
    hours: { monday: { open: "11:00", close: "22:00", isOpen: true }, tuesday: { open: "11:00", close: "22:00", isOpen: true }, wednesday: { open: "11:00", close: "22:00", isOpen: true }, thursday: { open: "11:00", close: "22:00", isOpen: true }, friday: { open: "11:00", close: "22:00", isOpen: true }, saturday: { open: "11:00", close: "22:00", isOpen: true }, sunday: { open: "11:00", close: "22:00", isOpen: true } },
    delivery: { fee: 0, minOrder: 75, estimatedTime: 25, radius: 6 },
    rating: { average: 4.8, count: 540 },
    commission: { rate: 10, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "4",
    name: "Pidecim",
    slug: "pidecim",
    description: "Karadeniz usulu pide ve lahmacun",
    ownerId: "owner4",
    address: { full: "Tunali Hilmi Cad. No:88", city: "Ankara", district: "Cankaya", lat: 39.9075, lng: 32.8611 },
    contact: { phone: "0312 555 0004", email: "info@pidecim.com" },
    cuisine: ["Pide", "Lahmacun", "Turk Mutfagi"],
    images: { logo: "", cover: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=800&h=500&fit=crop&auto=format", gallery: [] },
    hours: { monday: { open: "10:00", close: "23:00", isOpen: true }, tuesday: { open: "10:00", close: "23:00", isOpen: true }, wednesday: { open: "10:00", close: "23:00", isOpen: true }, thursday: { open: "10:00", close: "23:00", isOpen: true }, friday: { open: "10:00", close: "00:00", isOpen: true }, saturday: { open: "10:00", close: "00:00", isOpen: true }, sunday: { open: "10:00", close: "23:00", isOpen: true } },
    delivery: { fee: 7.99, minOrder: 40, estimatedTime: 25, radius: 5 },
    rating: { average: 4.6, count: 180 },
    commission: { rate: 12, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "5",
    name: "Tavukcu Baba",
    slug: "tavukcu-baba",
    description: "Citir tavuk ve izgara cesitleri",
    ownerId: "owner5",
    address: { full: "Alsancak Kordon No:12", city: "Izmir", district: "Konak", lat: 38.4361, lng: 27.1423 },
    contact: { phone: "0232 555 0005", email: "info@tavukcubaba.com" },
    cuisine: ["Tavuk", "Izgara", "Fast Food"],
    images: { logo: "", cover: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=800&h=500&fit=crop&auto=format", gallery: [] },
    hours: { monday: { open: "10:00", close: "23:00", isOpen: true }, tuesday: { open: "10:00", close: "23:00", isOpen: true }, wednesday: { open: "10:00", close: "23:00", isOpen: true }, thursday: { open: "10:00", close: "23:00", isOpen: true }, friday: { open: "10:00", close: "00:00", isOpen: true }, saturday: { open: "10:00", close: "00:00", isOpen: true }, sunday: { open: "10:00", close: "23:00", isOpen: true } },
    delivery: { fee: 5.99, minOrder: 35, estimatedTime: 20, radius: 4 },
    rating: { average: 4.4, count: 150 },
    commission: { rate: 15, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "6",
    name: "Balik Ekmek Evi",
    slug: "balik-ekmek-evi",
    description: "Taze balik ve deniz urunleri",
    ownerId: "owner6",
    address: { full: "Eminonu Meydani No:1", city: "Istanbul", district: "Fatih", lat: 41.0176, lng: 28.9684 },
    contact: { phone: "0212 555 0006", email: "info@balikekmek.com" },
    cuisine: ["Balik", "Deniz Urunleri"],
    images: { logo: "", cover: "https://images.unsplash.com/photo-1534604973-16b21c525822?w=800&h=500&fit=crop&auto=format", gallery: [] },
    hours: { monday: { open: "08:00", close: "20:00", isOpen: true }, tuesday: { open: "08:00", close: "20:00", isOpen: true }, wednesday: { open: "08:00", close: "20:00", isOpen: true }, thursday: { open: "08:00", close: "20:00", isOpen: true }, friday: { open: "08:00", close: "20:00", isOpen: true }, saturday: { open: "08:00", close: "21:00", isOpen: true }, sunday: { open: "09:00", close: "20:00", isOpen: false } },
    delivery: { fee: 14.99, minOrder: 80, estimatedTime: 35, radius: 3 },
    rating: { average: 4.7, count: 95 },
    commission: { rate: 10, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "7",
    name: "Ev Yemekleri Annecim",
    slug: "ev-yemekleri-annecim",
    description: "Evinizden uzakta ev yemegi tadi",
    ownerId: "owner7",
    address: { full: "Kizilay Mah. Bayindir Sok. No:5", city: "Ankara", district: "Cankaya", lat: 39.9208, lng: 32.8541 },
    contact: { phone: "0312 555 0007", email: "info@annecim.com" },
    cuisine: ["Ev Yemekleri", "Turk Mutfagi", "Corba"],
    images: { logo: "", cover: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=500&fit=crop&auto=format", gallery: [] },
    hours: { monday: { open: "11:00", close: "21:00", isOpen: true }, tuesday: { open: "11:00", close: "21:00", isOpen: true }, wednesday: { open: "11:00", close: "21:00", isOpen: true }, thursday: { open: "11:00", close: "21:00", isOpen: true }, friday: { open: "11:00", close: "21:00", isOpen: true }, saturday: { open: "11:00", close: "21:00", isOpen: true }, sunday: { open: "11:00", close: "21:00", isOpen: false } },
    delivery: { fee: 4.99, minOrder: 45, estimatedTime: 30, radius: 5 },
    rating: { average: 4.9, count: 420 },
    commission: { rate: 8, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: false },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "8",
    name: "Donerci Sahin Usta",
    slug: "donerci-sahin-usta",
    description: "El yapimi doner ve durum cesitleri",
    ownerId: "owner8",
    address: { full: "Cumhuriyet Meydani No:15", city: "Istanbul", district: "Uskudar", lat: 41.0266, lng: 29.0153 },
    contact: { phone: "0216 555 0008", email: "info@sahinusta.com" },
    cuisine: ["Doner", "Durum", "Turk Mutfagi"],
    images: { logo: "", cover: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&h=500&fit=crop&auto=format", gallery: [] },
    hours: { monday: { open: "10:00", close: "23:00", isOpen: true }, tuesday: { open: "10:00", close: "23:00", isOpen: true }, wednesday: { open: "10:00", close: "23:00", isOpen: true }, thursday: { open: "10:00", close: "23:00", isOpen: true }, friday: { open: "10:00", close: "00:00", isOpen: true }, saturday: { open: "10:00", close: "00:00", isOpen: true }, sunday: { open: "11:00", close: "23:00", isOpen: true } },
    delivery: { fee: 6.99, minOrder: 30, estimatedTime: 20, radius: 5 },
    rating: { average: 4.5, count: 280 },
    commission: { rate: 12, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
];

export const mockProducts: Record<string, (Product & { id: string })[]> = {
  "1": [
    { id: "p1", restaurantId: "1", name: "Whopper", description: "Ateste izgara 113g sigir eti, domates, marul, tursu, sogan, ketcap, mayonez", price: 129.99, categoryId: "burger", images: ["https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=400&fit=crop&auto=format"], variants: [{ id: "v1", name: "Menu", price: 159.99 }, { id: "v2", name: "King Boy Menu", price: 179.99 }], extras: [{ id: "e1", name: "Extra Peynir", price: 15 }, { id: "e2", name: "Bacon", price: 20 }], tags: ["burger", "izgara"], allergens: ["gluten", "sut"], isActive: true, isPopular: true, isFeatured: true, stock: 100, preparationTime: 10, rating: { average: 4.6, count: 200 }, createdAt: null as never, updatedAt: null as never },
    { id: "p2", restaurantId: "1", name: "Big King", description: "Iki kat sigir eti, ozel sos, marul, peynir, tursu, sogan", price: 139.99, categoryId: "burger", images: ["https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=400&fit=crop&auto=format"], variants: [{ id: "v1", name: "Menu", price: 169.99 }], extras: [{ id: "e1", name: "Extra Peynir", price: 15 }], tags: ["burger"], allergens: ["gluten", "sut"], isActive: true, isPopular: true, isFeatured: false, stock: 100, preparationTime: 10, rating: { average: 4.4, count: 150 }, createdAt: null as never, updatedAt: null as never },
    { id: "p3", restaurantId: "1", name: "Chicken Royale", description: "Citir tavuk fileto, mayonez, marul", price: 109.99, categoryId: "burger", images: ["https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400&h=400&fit=crop&auto=format"], variants: [{ id: "v1", name: "Menu", price: 139.99 }], extras: [{ id: "e1", name: "Aci Sos", price: 5 }], tags: ["tavuk", "burger"], allergens: ["gluten"], isActive: true, isPopular: false, isFeatured: false, stock: 100, preparationTime: 8, rating: { average: 4.3, count: 120 }, createdAt: null as never, updatedAt: null as never },
    { id: "p4", restaurantId: "1", name: "Patates Kizartmasi", description: "Citir altin sarisi patates", price: 39.99, categoryId: "yan-urunler", images: ["https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=400&fit=crop&auto=format"], variants: [{ id: "v1", name: "Buyuk", price: 49.99 }], extras: [], tags: ["patates", "yan urun"], allergens: ["gluten"], isActive: true, isPopular: true, isFeatured: false, stock: 200, preparationTime: 5, rating: { average: 4.2, count: 300 }, createdAt: null as never, updatedAt: null as never },
    { id: "p5", restaurantId: "1", name: "Sogan Halkasi", description: "Citir kaplamali sogan halkalari", price: 44.99, categoryId: "yan-urunler", images: ["https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=400&fit=crop&auto=format"], variants: [], extras: [], tags: ["sogan halkasi"], allergens: ["gluten"], isActive: true, isPopular: false, isFeatured: false, stock: 150, preparationTime: 5, rating: { average: 4.0, count: 80 }, createdAt: null as never, updatedAt: null as never },
    { id: "p6", restaurantId: "1", name: "Coca Cola", description: "330ml kutu", price: 24.99, categoryId: "icecekler", images: ["https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop&auto=format"], variants: [{ id: "v1", name: "500ml", price: 29.99 }], extras: [], tags: ["icecek", "kola"], allergens: [], isActive: true, isPopular: true, isFeatured: false, stock: 300, preparationTime: 1, rating: { average: 4.5, count: 100 }, createdAt: null as never, updatedAt: null as never },
  ],
  "3": [
    { id: "p10", restaurantId: "3", name: "Iskender Kebap", description: "Orijinal Iskender kebap, tereyagi, yogurt, domates sosu", price: 249.99, categoryId: "kebap", images: ["https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=400&fit=crop&auto=format"], variants: [{ id: "v1", name: "1.5 Porsiyon", price: 349.99 }, { id: "v2", name: "2 Porsiyon", price: 449.99 }], extras: [{ id: "e1", name: "Extra Yogurt", price: 25 }, { id: "e2", name: "Extra Tereyagi", price: 20 }], tags: ["kebap", "iskender"], allergens: ["gluten", "sut"], isActive: true, isPopular: true, isFeatured: true, stock: 50, preparationTime: 15, rating: { average: 4.9, count: 450 }, createdAt: null as never, updatedAt: null as never },
    { id: "p11", restaurantId: "3", name: "Adana Kebap", description: "Acili kiyma kebap, kozlenmis biber, domates", price: 199.99, categoryId: "kebap", images: ["https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400&h=400&fit=crop&auto=format"], variants: [{ id: "v1", name: "1.5 Porsiyon", price: 279.99 }], extras: [{ id: "e1", name: "Lavas", price: 10 }], tags: ["kebap", "adana"], allergens: ["gluten"], isActive: true, isPopular: true, isFeatured: false, stock: 80, preparationTime: 18, rating: { average: 4.7, count: 300 }, createdAt: null as never, updatedAt: null as never },
    { id: "p12", restaurantId: "3", name: "Ayran", description: "Taze yayik ayrani", price: 19.99, categoryId: "icecekler", images: ["https://images.unsplash.com/photo-1588710929895-a4bd84e9e7c5?w=400&h=400&fit=crop&auto=format"], variants: [], extras: [], tags: ["icecek", "ayran"], allergens: ["sut"], isActive: true, isPopular: true, isFeatured: false, stock: 200, preparationTime: 1, rating: { average: 4.8, count: 200 }, createdAt: null as never, updatedAt: null as never },
  ],
};

export function getMockProducts(restaurantId: string): (Product & { id: string })[] {
  return mockProducts[restaurantId] || mockProducts["1"] || [];
}
