import type { Restaurant, Product } from "@/types";

export const mockRestaurants: (Restaurant & { id: string })[] = [
  {
    id: "1",
    name: "Burger King",
    slug: "burger-king",
    description: "Ateşte ızgara lezzeti ile dünyanın en sevilen burgerleri",
    ownerId: "owner1",
    address: { full: "Bağdat Cad. No:123, Kadıköy", city: "İstanbul", district: "Kadıköy", lat: 40.9862, lng: 29.0558 },
    contact: { phone: "0212 555 0001", email: "info@burgerking.com.tr" },
    cuisine: ["Burger", "Fast Food"],
    images: { logo: "", cover: "", gallery: [] },
    hours: { monday: { open: "10:00", close: "23:00", isOpen: true }, tuesday: { open: "10:00", close: "23:00", isOpen: true }, wednesday: { open: "10:00", close: "23:00", isOpen: true }, thursday: { open: "10:00", close: "23:00", isOpen: true }, friday: { open: "10:00", close: "00:00", isOpen: true }, saturday: { open: "10:00", close: "00:00", isOpen: true }, sunday: { open: "11:00", close: "23:00", isOpen: true } },
    delivery: { fee: 9.99, minOrder: 50, estimatedTime: 30, radius: 5 },
    rating: { average: 4.5, count: 320 },
    commission: { rate: 15, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "2",
    name: "Pizza Lazza",
    slug: "pizza-lazza",
    description: "İtalyan usulü el yapımı pizzalar",
    ownerId: "owner2",
    address: { full: "İstiklal Cad. No:45, Beyoğlu", city: "İstanbul", district: "Beyoğlu", lat: 41.0340, lng: 28.9775 },
    contact: { phone: "0212 555 0002", email: "info@pizzalazza.com" },
    cuisine: ["Pizza", "İtalyan", "Makarna"],
    images: { logo: "", cover: "", gallery: [] },
    hours: { monday: { open: "11:00", close: "23:00", isOpen: true }, tuesday: { open: "11:00", close: "23:00", isOpen: true }, wednesday: { open: "11:00", close: "23:00", isOpen: true }, thursday: { open: "11:00", close: "23:00", isOpen: true }, friday: { open: "11:00", close: "00:00", isOpen: true }, saturday: { open: "11:00", close: "00:00", isOpen: true }, sunday: { open: "12:00", close: "23:00", isOpen: true } },
    delivery: { fee: 12.99, minOrder: 60, estimatedTime: 35, radius: 4 },
    rating: { average: 4.3, count: 210 },
    commission: { rate: 12, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "3",
    name: "Kebapçı İskender",
    slug: "kebapci-iskender",
    description: "1867'den beri İskender kebabın orijinal adresi",
    ownerId: "owner3",
    address: { full: "Atatürk Cad. No:7, Osmangazi", city: "Bursa", district: "Osmangazi", lat: 40.1885, lng: 29.0610 },
    contact: { phone: "0224 555 0003", email: "info@iskender.com.tr" },
    cuisine: ["Kebap", "Türk Mutfağı"],
    images: { logo: "", cover: "", gallery: [] },
    hours: { monday: { open: "11:00", close: "22:00", isOpen: true }, tuesday: { open: "11:00", close: "22:00", isOpen: true }, wednesday: { open: "11:00", close: "22:00", isOpen: true }, thursday: { open: "11:00", close: "22:00", isOpen: true }, friday: { open: "11:00", close: "22:00", isOpen: true }, saturday: { open: "11:00", close: "22:00", isOpen: true }, sunday: { open: "11:00", close: "22:00", isOpen: true } },
    delivery: { fee: 0, minOrder: 75, estimatedTime: 25, radius: 6 },
    rating: { average: 4.8, count: 540 },
    commission: { rate: 10, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "4",
    name: "Pidecim",
    slug: "pidecim",
    description: "Karadeniz usulü pide ve lahmacun",
    ownerId: "owner4",
    address: { full: "Tunalı Hilmi Cad. No:88", city: "Ankara", district: "Çankaya", lat: 39.9075, lng: 32.8611 },
    contact: { phone: "0312 555 0004", email: "info@pidecim.com" },
    cuisine: ["Pide", "Lahmacun", "Türk Mutfağı"],
    images: { logo: "", cover: "", gallery: [] },
    hours: { monday: { open: "10:00", close: "23:00", isOpen: true }, tuesday: { open: "10:00", close: "23:00", isOpen: true }, wednesday: { open: "10:00", close: "23:00", isOpen: true }, thursday: { open: "10:00", close: "23:00", isOpen: true }, friday: { open: "10:00", close: "00:00", isOpen: true }, saturday: { open: "10:00", close: "00:00", isOpen: true }, sunday: { open: "10:00", close: "23:00", isOpen: true } },
    delivery: { fee: 7.99, minOrder: 40, estimatedTime: 25, radius: 5 },
    rating: { average: 4.6, count: 180 },
    commission: { rate: 12, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "5",
    name: "Tavukçu Baba",
    slug: "tavukcu-baba",
    description: "Çıtır tavuk ve ızgara çeşitleri",
    ownerId: "owner5",
    address: { full: "Alsancak Kordon No:12", city: "İzmir", district: "Konak", lat: 38.4361, lng: 27.1423 },
    contact: { phone: "0232 555 0005", email: "info@tavukcubaba.com" },
    cuisine: ["Tavuk", "Izgara", "Fast Food"],
    images: { logo: "", cover: "", gallery: [] },
    hours: { monday: { open: "10:00", close: "23:00", isOpen: true }, tuesday: { open: "10:00", close: "23:00", isOpen: true }, wednesday: { open: "10:00", close: "23:00", isOpen: true }, thursday: { open: "10:00", close: "23:00", isOpen: true }, friday: { open: "10:00", close: "00:00", isOpen: true }, saturday: { open: "10:00", close: "00:00", isOpen: true }, sunday: { open: "10:00", close: "23:00", isOpen: true } },
    delivery: { fee: 5.99, minOrder: 35, estimatedTime: 20, radius: 4 },
    rating: { average: 4.4, count: 150 },
    commission: { rate: 15, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "6",
    name: "Balık Ekmek Evi",
    slug: "balik-ekmek-evi",
    description: "Taze balık ve deniz ürünleri",
    ownerId: "owner6",
    address: { full: "Eminönü Meydanı No:1", city: "İstanbul", district: "Fatih", lat: 41.0176, lng: 28.9684 },
    contact: { phone: "0212 555 0006", email: "info@balikekmek.com" },
    cuisine: ["Balık", "Deniz Ürünleri"],
    images: { logo: "", cover: "", gallery: [] },
    hours: { monday: { open: "08:00", close: "20:00", isOpen: true }, tuesday: { open: "08:00", close: "20:00", isOpen: true }, wednesday: { open: "08:00", close: "20:00", isOpen: true }, thursday: { open: "08:00", close: "20:00", isOpen: true }, friday: { open: "08:00", close: "20:00", isOpen: true }, saturday: { open: "08:00", close: "21:00", isOpen: true }, sunday: { open: "09:00", close: "20:00", isOpen: false } },
    delivery: { fee: 14.99, minOrder: 80, estimatedTime: 35, radius: 3 },
    rating: { average: 4.7, count: 95 },
    commission: { rate: 10, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "7",
    name: "Ev Yemekleri Annecim",
    slug: "ev-yemekleri-annecim",
    description: "Evinizden uzakta ev yemeği tadı",
    ownerId: "owner7",
    address: { full: "Kızılay Mah. Bayındır Sok. No:5", city: "Ankara", district: "Çankaya", lat: 39.9208, lng: 32.8541 },
    contact: { phone: "0312 555 0007", email: "info@annecim.com" },
    cuisine: ["Ev Yemekleri", "Türk Mutfağı", "Çorba"],
    images: { logo: "", cover: "", gallery: [] },
    hours: { monday: { open: "11:00", close: "21:00", isOpen: true }, tuesday: { open: "11:00", close: "21:00", isOpen: true }, wednesday: { open: "11:00", close: "21:00", isOpen: true }, thursday: { open: "11:00", close: "21:00", isOpen: true }, friday: { open: "11:00", close: "21:00", isOpen: true }, saturday: { open: "11:00", close: "21:00", isOpen: true }, sunday: { open: "11:00", close: "21:00", isOpen: false } },
    delivery: { fee: 4.99, minOrder: 45, estimatedTime: 30, radius: 5 },
    rating: { average: 4.9, count: 420 },
    commission: { rate: 8, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: false },
    createdAt: null as never,
    updatedAt: null as never,
  },
  {
    id: "8",
    name: "Dönerci Şahin Usta",
    slug: "donerci-sahin-usta",
    description: "El yapımı döner ve dürüm çeşitleri",
    ownerId: "owner8",
    address: { full: "Cumhuriyet Meydanı No:15", city: "İstanbul", district: "Üsküdar", lat: 41.0266, lng: 29.0153 },
    contact: { phone: "0216 555 0008", email: "info@sahinusta.com" },
    cuisine: ["Döner", "Dürüm", "Türk Mutfağı"],
    images: { logo: "", cover: "", gallery: [] },
    hours: { monday: { open: "10:00", close: "23:00", isOpen: true }, tuesday: { open: "10:00", close: "23:00", isOpen: true }, wednesday: { open: "10:00", close: "23:00", isOpen: true }, thursday: { open: "10:00", close: "23:00", isOpen: true }, friday: { open: "10:00", close: "00:00", isOpen: true }, saturday: { open: "10:00", close: "00:00", isOpen: true }, sunday: { open: "11:00", close: "23:00", isOpen: true } },
    delivery: { fee: 6.99, minOrder: 30, estimatedTime: 20, radius: 5 },
    rating: { average: 4.5, count: 280 },
    commission: { rate: 12, type: "percentage" },
    status: "active",
    features: { hasPickup: true, hasDelivery: true, acceptsCard: true },
    createdAt: null as never,
    updatedAt: null as never,
  },
];

export const mockProducts: Record<string, (Product & { id: string })[]> = {
  "1": [
    { id: "p1", restaurantId: "1", name: "Whopper", description: "Ateşte ızgara 113g sığır eti, domates, marul, turşu, soğan, ketçap, mayonez", price: 129.99, categoryId: "burger", images: [], variants: [{ id: "v1", name: "Menü", price: 159.99 }, { id: "v2", name: "King Boy Menü", price: 179.99 }], extras: [{ id: "e1", name: "Extra Peynir", price: 15 }, { id: "e2", name: "Bacon", price: 20 }], tags: ["burger", "ızgara"], allergens: ["gluten", "süt"], isActive: true, isPopular: true, isFeatured: true, stock: 100, preparationTime: 10, rating: { average: 4.6, count: 200 }, createdAt: null as never, updatedAt: null as never },
    { id: "p2", restaurantId: "1", name: "Big King", description: "İki kat sığır eti, özel sos, marul, peynir, turşu, soğan", price: 139.99, categoryId: "burger", images: [], variants: [{ id: "v1", name: "Menü", price: 169.99 }], extras: [{ id: "e1", name: "Extra Peynir", price: 15 }], tags: ["burger"], allergens: ["gluten", "süt"], isActive: true, isPopular: true, isFeatured: false, stock: 100, preparationTime: 10, rating: { average: 4.4, count: 150 }, createdAt: null as never, updatedAt: null as never },
    { id: "p3", restaurantId: "1", name: "Chicken Royale", description: "Çıtır tavuk fileto, mayonez, marul", price: 109.99, categoryId: "burger", images: [], variants: [{ id: "v1", name: "Menü", price: 139.99 }], extras: [{ id: "e1", name: "Acı Sos", price: 5 }], tags: ["tavuk", "burger"], allergens: ["gluten"], isActive: true, isPopular: false, isFeatured: false, stock: 100, preparationTime: 8, rating: { average: 4.3, count: 120 }, createdAt: null as never, updatedAt: null as never },
    { id: "p4", restaurantId: "1", name: "Patates Kızartması", description: "Çıtır altın sarısı patates", price: 39.99, categoryId: "yan-urunler", images: [], variants: [{ id: "v1", name: "Büyük", price: 49.99 }], extras: [], tags: ["patates", "yan ürün"], allergens: ["gluten"], isActive: true, isPopular: true, isFeatured: false, stock: 200, preparationTime: 5, rating: { average: 4.2, count: 300 }, createdAt: null as never, updatedAt: null as never },
    { id: "p5", restaurantId: "1", name: "Soğan Halkası", description: "Çıtır kaplamalı soğan halkaları", price: 44.99, categoryId: "yan-urunler", images: [], variants: [], extras: [], tags: ["soğan halkası"], allergens: ["gluten"], isActive: true, isPopular: false, isFeatured: false, stock: 150, preparationTime: 5, rating: { average: 4.0, count: 80 }, createdAt: null as never, updatedAt: null as never },
    { id: "p6", restaurantId: "1", name: "Coca Cola", description: "330ml kutu", price: 24.99, categoryId: "icecekler", images: [], variants: [{ id: "v1", name: "500ml", price: 29.99 }], extras: [], tags: ["içecek", "kola"], allergens: [], isActive: true, isPopular: true, isFeatured: false, stock: 300, preparationTime: 1, rating: { average: 4.5, count: 100 }, createdAt: null as never, updatedAt: null as never },
  ],
  "3": [
    { id: "p10", restaurantId: "3", name: "İskender Kebap", description: "Orijinal İskender kebap, tereyağı, yoğurt, domates sosu", price: 249.99, categoryId: "kebap", images: [], variants: [{ id: "v1", name: "1.5 Porsiyon", price: 349.99 }, { id: "v2", name: "2 Porsiyon", price: 449.99 }], extras: [{ id: "e1", name: "Extra Yoğurt", price: 25 }, { id: "e2", name: "Extra Tereyağı", price: 20 }], tags: ["kebap", "iskender"], allergens: ["gluten", "süt"], isActive: true, isPopular: true, isFeatured: true, stock: 50, preparationTime: 15, rating: { average: 4.9, count: 450 }, createdAt: null as never, updatedAt: null as never },
    { id: "p11", restaurantId: "3", name: "Adana Kebap", description: "Acılı kıyma kebap, közlenmiş biber, domates", price: 199.99, categoryId: "kebap", images: [], variants: [{ id: "v1", name: "1.5 Porsiyon", price: 279.99 }], extras: [{ id: "e1", name: "Lavaş", price: 10 }], tags: ["kebap", "adana"], allergens: ["gluten"], isActive: true, isPopular: true, isFeatured: false, stock: 80, preparationTime: 18, rating: { average: 4.7, count: 300 }, createdAt: null as never, updatedAt: null as never },
    { id: "p12", restaurantId: "3", name: "Ayran", description: "Taze yayık ayranı", price: 19.99, categoryId: "icecekler", images: [], variants: [], extras: [], tags: ["içecek", "ayran"], allergens: ["süt"], isActive: true, isPopular: true, isFeatured: false, stock: 200, preparationTime: 1, rating: { average: 4.8, count: 200 }, createdAt: null as never, updatedAt: null as never },
  ],
};

export function getMockProducts(restaurantId: string): (Product & { id: string })[] {
  return mockProducts[restaurantId] || mockProducts["1"] || [];
}
